apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: bindings-with-output
spec:
  version: "v1.0.0"
  image: openfunctiondev/bindings-with-output:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "BindingsOutput"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/OpenFuncAsync/bindings/with-output/"
      revision: "main"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: cron
            component: cron
            type: bindings
        outputs:
          - name: sample
            component: sample-topic
            type: bindings
            operation: "create"
        annotations:
          "dapr.io/log-level": "debug"
        components:
          cron:
            type: bindings.cron
            version: v1
            metadata:
            - name: schedule
              value: "@every 2s"
          sample-topic:
            type: bindings.kafka
            version: v1
            metadata:
            - name: brokers
              value: "kafka-bindings-server-kafka-brokers:9092"
            - name: topics
              value: sample
            - name: consumerGroup
              value: group1
            - name: publishTopic
              value: sample
            - name: authRequired
              value: "false"
