apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: input-binding
spec:
  version: "v1.0.0"
  image: openfunctiondev/bindings-output-target:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "Target"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Async/bindings/input-binding"
      revision: "main"
  serving:
    runtime: async
    scaleOptions:
      minReplicas: 0
      maxReplicas: 10 
      keda:
        scaledObject:
          pollingInterval: 15
          # minReplicaCount: 0
          # maxReplicaCount: 10
          cooldownPeriod: 30
    triggers:
      - type: kafka
        metadata:
          topic: sample-topic
          bootstrapServers: kafka-server-kafka-brokers.default.svc:9092
          consumerGroup: output-target
          lagThreshold: "10"
    inputs:
      - name: greeting
        component: target-topic
    bindings:
      target-topic:
        type: bindings.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: topics
            value: "sample-topic"
          - name: consumerGroup
            value: "output-target"
          - name: publishTopic
            value: "sample-topic"
          - name: authRequired
            value: "false"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
