apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-ko
spec:
  version: "v1.0.0"
  image: "openfunctiondev/sample-ko:latest"
  imageCredentials:
    name: push-secret
  #port: 8080 # default to 8080
  build:
    builder: golang:1.17
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "apps/with-dockerfile"
      revision: "release-0.6"
    shipwright:
      strategy:
        name: ko
        kind: ClusterBuildStrategy
  serving:
    runtime: knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
