apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: autoscaling-subscriber
spec:
  version: "v1.0.0"
  image: openfunctiondev/autoscaling-subscriber:v0.4.0
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.3.0
    env:
      FUNC_NAME: "Subscriber"
      FUNC_GOPROXY: "https://goproxy.cn"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "v0.4.0/functions/OpenFuncAsync/pubsub/subscriber"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: subscriber
            component: autoscaling-subscriber
            type: pubsub
            topic: metric
        annotations:
          dapr.io/log-level: "debug"
        components:
          autoscaling-subscriber:
            type: pubsub.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-pubsub-server-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: allowedTopics
                value: "metric"
              - name: consumerID
                value: "autoscaling-subscriber"
      keda:
        scaledObject:
          pollingInterval: 15
          minReplicaCount: 0
          maxReplicaCount: 10
          cooldownPeriod: 30
          triggers:
            - type: kafka
              metadata:
                topic: metric
                bootstrapServers: kafka-pubsub-server-kafka-brokers.default.svc.cluster.local:9092
                consumerGroup: autoscaling-subscriber
                lagThreshold: "10"

