apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: function-sample
spec:
  version: "v1.0.0"
  image: "openfunctiondev/sample-go-func:v0.5.0"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder:v1
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_TYPE: "http"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "v0.5.0/functions/Knative/hello-world-go"
  serving:
    runtime: Knative # default to Knative
#    template:
#      containers:
#       - name: function
#          # Set imagePullPolicy if needed
#          imagePullPolicy: Always
